### ISSUE TITLE
Panick in cumulus-pallet-parachain-system on v0.10.0 

### ISSUE THREAD

**Issue by SimonKraus** [bifrost-finance/bifrost#1258]
After upgrading our collator to release v0.10.0 we're seeing Panicks in cumulus-pallet-parachain-system.

See error below:

```
Jun 05 20:37:00 bnc1 bifrost[1100869]: 2024-06-05 20:37:00 [Parachain🌈] panicked at /home/builder/cargo/registry/src/index.crates.io-6f17d22bba15001f/cumulus-pallet-parachain-system-0.7.0/src/lib.rs:1283:17:
Jun 05 20:37:00 bnc1 bifrost[1100869]: assertion `left == right` failed: expected parent to be included
Jun 05 20:37:00 bnc1 bifrost[1100869]:   left: 0x328acd68707108be6bd097e891f949e7ccec74f64194920c5172ebc38614846a
Jun 05 20:37:00 bnc1 bifrost[1100869]:  right: 0x457cca6cf3dcd1a726dc36b6ac777635c011568cb6cb2af9bf0486b1163e0ed5
Jun 05 20:37:00 bnc1 bifrost[1100869]: 2024-06-05 20:37:00 [Parachain🌈] 1 storage transactions are left open by the runtime. Those will be rolled back.
Jun 05 20:37:00 bnc1 bifrost[1100869]: 2024-06-05 20:37:00 [Parachain🌈] 1 storage transactions are left open by the runtime. Those will be rolled back.
Jun 05 20:37:00 bnc1 bifrost[1100869]: 2024-06-05 20:37:00 [Parachain🌈] ❗️ Inherent extrinsic returned unexpected error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
Jun 05 20:37:00 bnc1 bifrost[1100869]: WASM backtrace:
Jun 05 20:37:00 bnc1 bifrost[1100869]: error while executing at wasm backtrace:
Jun 05 20:37:00 bnc1 bifrost[1100869]:     0: 0x7f2799 - <unknown>!rust_begin_unwind
Jun 05 20:37:00 bnc1 bifrost[1100869]:     1: 0x76bb7e - <unknown>!core::panicking::panic_fmt::h7d22643b0becf577
Jun 05 20:37:00 bnc1 bifrost[1100869]:     2: 0x76c5d6 - <unknown>!core::panicking::assert_failed_inner::hf53be49d983c07ca
Jun 05 20:37:00 bnc1 bifrost[1100869]:     3: 0x270df6 - <unknown>!core::panicking::assert_failed::h2d65652b727ca1d4
Jun 05 20:37:00 bnc1 bifrost[1100869]:     4: 0x42bfe0 - <unknown>!cumulus_pallet_parachain_system::<impl cumulus_pallet_parachain_system::pallet::Pallet<T>>::maybe_drop_included_ancestors::h5cff18225f92ef14
Jun 05 20:37:00 bnc1 bifrost[1100869]:     5: 0x153ba8 - <unknown>!frame_support::storage::transactional::with_transaction::h73feacd6468b1b82
Jun 05 20:37:00 bnc1 bifrost[1100869]:     6: 0x2b7939 - <unknown>!<cumulus_pallet_parachain_system::pallet::Call<T> as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::{{closure}}::hfeacde750a068210
Jun 05 20:37:00 bnc1 bifrost[1100869]:     7: 0x2c9460 - <unknown>!environmental::local_key::LocalKey<T>::with::hca7131440c81cfed
Jun 05 20:37:00 bnc1 bifrost[1100869]:     8: 0x64cc47 - <unknown>!frame_support::dispatch_context::run_in_context::hb8978b6f5b556200
Jun 05 20:37:00 bnc1 bifrost[1100869]:     9: 0x1777f - <unknown>!<bifrost_kusama_runtime::RuntimeCall as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::h3db95bc5caa5bda3
Jun 05 20:37:00 bnc1 bifrost[1100869]:    10: 0x28873 - <unknown>!<bifrost_kusama_runtime::RuntimeCall as sp_runtime::traits::Dispatchable>::dispatch::hf58a945d9c0617d8
Jun 05 20:37:00 bnc1 bifrost[1100869]:    11: 0x2b82b9 - <unknown>!<sp_runtime::generic::checked_extrinsic::CheckedExtrinsic<AccountId,Call,Extra> as sp_runtime::traits::Applyable>::apply::he7b5b0f91f8e98ce
Jun 05 20:37:00 bnc1 bifrost[1100869]:    12: 0x516121 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::apply_extrinsic::ha8a394cb3b1fe4e2
Jun 05 20:37:00 bnc1 bifrost[1100869]:    13: 0x756a9d - <unknown>!BlockBuilder_apply_extrinsic. Dropping.
Jun 05 20:37:00 bnc1 bifrost[1100869]: 2024-06-05 20:37:00 [Parachain🌈] panicked at /home/builder/cargo/registry/src/index.crates.io-6f17d22bba15001f/cumulus-pallet-parachain-system-0.7.0/src/lib.rs:265:18:
Jun 05 20:37:00 bnc1 bifrost[1100869]: set_validation_data inherent needs to be present in every block!
Jun 05 20:37:00 bnc1 bifrost[1100869]: 2024-06-05 20:37:00 [Parachain🌈] err=Error { inner: Proposing
Jun 05 20:37:00 bnc1 bifrost[1100869]: Caused by:
Jun 05 20:37:00 bnc1 bifrost[1100869]:     0: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
Jun 05 20:37:00 bnc1 bifrost[1100869]:        WASM backtrace:
Jun 05 20:37:00 bnc1 bifrost[1100869]:        error while executing at wasm backtrace:
Jun 05 20:37:00 bnc1 bifrost[1100869]:            0: 0x7f2799 - <unknown>!rust_begin_unwind
Jun 05 20:37:00 bnc1 bifrost[1100869]:            1: 0x76bb7e - <unknown>!core::panicking::panic_fmt::h7d22643b0becf577
Jun 05 20:37:00 bnc1 bifrost[1100869]:            2: 0x76c211 - <unknown>!core::option::expect_failed::hd82c6d6933db2709
Jun 05 20:37:00 bnc1 bifrost[1100869]:            3: 0x3f30d4 - <unknown>!<(TupleElement0,TupleElement1,TupleElement2,TupleElement3,TupleElement4,TupleElement5,TupleElement6,TupleElement7,TupleElement8,TupleElement9,TupleElement10,TupleElement11,TupleElement12,TupleElement13,TupleElement14,TupleElement15,TupleElement16,TupleElement17,TupleElement18,TupleElement19,TupleElement20,TupleElement21,TupleElement22,TupleElement23,TupleElement24,TupleElement25,TupleElement26,TupleElement27,TupleElement28,TupleElement29,TupleElement30,TupleElement31,TupleElement32,TupleElement33,TupleElement34,TupleElement35,TupleElement36,TupleElement37,TupleElement38,TupleElement39,TupleElement40,TupleElement41,TupleElement42,TupleElement43,TupleElement44,TupleElement45,TupleElement46,TupleElement47,TupleElement48,TupleElement49,TupleElement50,TupleElement51,TupleElement52,TupleElement53,TupleElement54,TupleElement55,TupleElement56,TupleElement57,TupleElement58,TupleElement59,TupleElement60,TupleElement61,TupleElement62,TupleElement63,TupleElement64,TupleElement65,TupleElement66,TupleElement67,TupleElement68,TupleElement69,TupleElement70) as frame_support::traits::hooks::OnFinalize<BlockNumber>>::on_finalize::hed27b1d078b9f84b
Jun 05 20:37:00 bnc1 bifrost[1100869]:            4: 0x51655c - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::idle_and_finalize_hook::hc9829f4708ff898d
Jun 05 20:37:00 bnc1 bifrost[1100869]:            5: 0x756b64 - <unknown>!BlockBuilder_finalize_block
Jun 05 20:37:00 bnc1 bifrost[1100869]:     1: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
Jun 05 20:37:00 bnc1 bifrost[1100869]:        WASM backtrace:
Jun 05 20:37:00 bnc1 bifrost[1100869]:        error while executing at wasm backtrace:
Jun 05 20:37:00 bnc1 bifrost[1100869]:            0: 0x7f2799 - <unknown>!rust_begin_unwind
Jun 05 20:37:00 bnc1 bifrost[1100869]:            1: 0x76bb7e - <unknown>!core::panicking::panic_fmt::h7d22643b0becf577
Jun 05 20:37:00 bnc1 bifrost[1100869]:            2: 0x76c211 - <unknown>!core::option::expect_failed::hd82c6d6933db2709
Jun 05 20:37:00 bnc1 bifrost[1100869]:            3: 0x3f30d4 - <unknown>!<(TupleElement0,TupleElement1,TupleElement2,TupleElement3,TupleElement4,TupleElement5,TupleElement6,TupleElement7,TupleElement8,TupleElement9,TupleElement10,TupleElement11,TupleElement12,TupleElement13,TupleElement14,TupleElement15,TupleElement16,TupleElement17,TupleElement18,TupleElement19,TupleElement20,TupleElement21,TupleElement22,TupleElement23,TupleElement24,TupleElement25,TupleElement26,TupleElement27,TupleElement28,TupleElement29,TupleElement30,TupleElement31,TupleElement32,TupleElement33,TupleElement34,TupleElement35,TupleElement36,TupleElement37,TupleElement38,TupleElement39,TupleElement40,TupleElement41,TupleElement42,TupleElement43,TupleElement44,TupleElement45,TupleElement46,TupleElement47,TupleElement48,TupleElement49,TupleElement50,TupleElement51,TupleElement52,TupleElement53,TupleElement54,TupleElement55,TupleElement56,TupleElement57,TupleElement58,TupleElement59,TupleElement60,TupleElement61,TupleElement62,TupleElement63,TupleElement64,TupleElement65,TupleElement66,TupleElement67,TupleElement68,TupleElement69,TupleElement70) as frame_support::traits::hooks::OnFinalize<BlockNumber>>::on_finalize::hed27b1d078b9f84b
Jun 05 20:37:00 bnc1 bifrost[1100869]:            4: 0x51655c - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::idle_and_finalize_hook::hc9829f4708ff898d
Jun 05 20:37:00 bnc1 bifrost[1100869]:            5: 0x756b64 - <unknown>!BlockBuilder_finalize_block }
```

Hit me up if you need more information.

**Comment by SimonKraus** [comment]
((Error always pops up before the collator proposes a block))
