### ISSUE TITLE
Errors during block import

### ISSUE THREAD

**Issue by nazar-pc** [bifrost-finance/bifrost#382]
I'm running an archival node with following docker-compose.yml:
```yml
version: '2'

services:
  bifrost:
    image: bifrostnetwork/bifrost
    ports:
      - 19947:9944 # ws port
    volumes:
      - ./bifrost:/data
    command: [
      "--chain", "bifrost",
      "--pruning", "archive",
      "--ws-external",
      "--rpc-external",
      "--rpc-cors", "all"
    ]
```

And I noticed that there are some errors. Don't know or care too much, but I hope it is useful for you folks:
```
bifrost_1  | 2021-10-28 14:51:54 [Relaychain] ✨ Imported #9852210 (0x34af…9521)    
bifrost_1  | 2021-10-28 14:51:54 [Parachain🌈] 💤 Idle (1 peers), best: #654402 (0xa84d…0250), finalized #654402 (0xa84d…0250), ⬇ 1.1kiB/s ⬆ 1.4kiB/s    
bifrost_1  | 2021-10-28 14:51:58 [Relaychain] 💤 Idle (40 peers), best: #9852210 (0x34af…9521), finalized #9852207 (0x37c3…b167), ⬇ 217.9kiB/s ⬆ 577.1kiB/s    
bifrost_1  | 2021-10-28 14:51:59 [Parachain🌈] ⚙️  Syncing  0.0 bps, target=#655914 (3 peers), best: #654402 (0xa84d…0250), finalized #654402 (0xa84d…0250), ⬇ 3.3kiB/s ⬆ 2.0kiB/s    
bifrost_1  | 2021-10-28 14:52:00 [Relaychain] ✨ Imported #9852211 (0xb677…80f7)    
bifrost_1  | 2021-10-28 14:52:00 [Relaychain] ✨ Imported #9852211 (0xed24…7268)    
bifrost_1  | 2021-10-28 14:52:01 [Parachain🌈] panicked at 'Storage root must match that calculated.', /cargo-home/git/checkouts/substrate-7e08433d4c370a21/57346f6/frame/executive/src/lib.rs:503:9    
bifrost_1  | 2021-10-28 14:52:01 [Parachain🌈] Block prepare storage changes error:
bifrost_1  | RuntimeApiError(Application(Execution(Other("Wasm execution trapped: wasm trap: unreachable\nwasm backtrace:\n    0: 0x32ef8a - <unknown>!rust_begin_unwind\n    1: 0x24dd - <unknown>!core::panicking::panic_fmt::h3ab5417155b7ba3b\n    2: 0x1b71 - <unknown>!core::panicking::panic::h5bfdfaa3db9a4b4a\n    3: 0x1e77cf - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block::h06ad04c865112a1b\n    4: 0x1f5ab1 - <unknown>!Core_execute_block\nnote: run with `WASMTIME_BACKTRACE_DETAILS=1` environment variable to display more information\n"))))    
bifrost_1  | 2021-10-28 14:52:01 [Parachain🌈] 💔 Error importing block 0xdf70ff07d9a16bd9c4887ace8d64d68e033d8421f3189199dc6cae6188f70826: Err(Other(ClientImport("Error at calling runtime api: Execution failed: Other(\"Wasm execution trapped: wasm trap: unreachable\\nwasm backtrace:\\n    0: 0x32ef8a - <unknown>!rust_begin_unwind\\n    1: 0x24dd - <unknown>!core::panicking::panic_fmt::h3ab5417155b7ba3b\\n    2: 0x1b71 - <unknown>!core::panicking::panic::h5bfdfaa3db9a4b4a\\n    3: 0x1e77cf - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block::h06ad04c865112a1b\\n    4: 0x1f5ab1 - <unknown>!Core_execute_block\\nnote: run with `WASMTIME_BACKTRACE_DETAILS=1` environment variable to display more information\\n\")")))    
bifrost_1  | 2021-10-28 14:52:03 [Relaychain] 💤 Idle (40 peers), best: #9852211 (0xb677…80f7), finalized #9852208 (0xfffb…fa38), ⬇ 268.9kiB/s ⬆ 537.8kiB/s    
bifrost_1  | 2021-10-28 14:52:04 [Parachain🌈] ⚙️  Syncing  0.0 bps, target=#655916 (2 peers), best: #654402 (0xa84d…0250), finalized #654402 (0xa84d…0250), ⬇ 118.1kiB/s ⬆ 1.1kiB/s    
bifrost_1  | 2021-10-28 14:52:04 [Parachain🌈] panicked at 'Storage root must match that calculated.', /cargo-home/git/checkouts/substrate-7e08433d4c370a21/57346f6/frame/executive/src/lib.rs:503:9    
bifrost_1  | 2021-10-28 14:52:04 [Parachain🌈] Block prepare storage changes error:
bifrost_1  | RuntimeApiError(Application(Execution(Other("Wasm execution trapped: wasm trap: unreachable\nwasm backtrace:\n    0: 0x32ef8a - <unknown>!rust_begin_unwind\n    1: 0x24dd - <unknown>!core::panicking::panic_fmt::h3ab5417155b7ba3b\n    2: 0x1b71 - <unknown>!core::panicking::panic::h5bfdfaa3db9a4b4a\n    3: 0x1e77cf - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block::h06ad04c865112a1b\n    4: 0x1f5ab1 - <unknown>!Core_execute_block\nnote: run with `WASMTIME_BACKTRACE_DETAILS=1` environment variable to display more information\n"))))    
bifrost_1  | 2021-10-28 14:52:04 [Parachain🌈] 💔 Error importing block 0xdf70ff07d9a16bd9c4887ace8d64d68e033d8421f3189199dc6cae6188f70826: Err(Other(ClientImport("Error at calling runtime api: Execution failed: Other(\"Wasm execution trapped: wasm trap: unreachable\\nwasm backtrace:\\n    0: 0x32ef8a - <unknown>!rust_begin_unwind\\n    1: 0x24dd - <unknown>!core::panicking::panic_fmt::h3ab5417155b7ba3b\\n    2: 0x1b71 - <unknown>!core::panicking::panic::h5bfdfaa3db9a4b4a\\n    3: 0x1e77cf - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block::h06ad04c865112a1b\\n    4: 0x1f5ab1 - <unknown>!Core_execute_block\\nnote: run with `WASMTIME_BACKTRACE_DETAILS=1` environment variable to display more information\\n\")")))    
bifrost_1  | 2021-10-28 14:52:06 [Relaychain] ✨ Imported #9852212 (0x40ba…839f)    
bifrost_1  | 2021-10-28 14:52:06 [Relaychain] ♻️  Reorg on #9852212,0x40ba…839f to #9852212,0x6cd6…403a, common ancestor #9852211,0xb677…80f7    
bifrost_1  | 2021-10-28 14:52:06 [Relaychain] ✨ Imported #9852212 (0x6cd6…403a)    
bifrost_1  | 2021-10-28 14:52:08 [Relaychain] 💤 Idle (40 peers), best: #9852212 (0x6cd6…403a), finalized #9852208 (0xfffb…fa38), ⬇ 461.1kiB/s ⬆ 494.2kiB/s    
bifrost_1  | 2021-10-28 14:52:09 [Parachain🌈] 💤 Idle (1 peers), best: #654402 (0xa84d…0250), finalized #654402 (0xa84d…0250), ⬇ 57.1kiB/s ⬆ 1.1kiB/s    
bifrost_1  | 2021-10-28 14:52:13 [Relaychain] 💤 Idle (39 peers), best: #9852212 (0x6cd6…403a), finalized #9852209 (0xae03…f9ce), ⬇ 306.6kiB/s ⬆ 406.6kiB/s    
bifrost_1  | 2021-10-28 14:52:13 [Relaychain] ✨ Imported #9852213 (0xda6f…1fc8)    
```

**Comment by ark930** [comment]
The mainnet chain spec of Bifrost  is contained in docker image which located in `/spec/bifrost.json`. Please try to replace `--chain bifrost` to `--chain /spec/bifrost.json`
